- name: users | Creating Percona Backup User
  shell: "mysql -e \"CREATE USER IF NOT EXISTS '{{ percona_xtrabackup_user.name }}'@'localhost' IDENTIFIED WITH mysql_native_password BY '{{ percona_xtrabackup_user.password }}';\" -uroot -p'{{ passwd_mysql_root }}'"

# If you would grant to user and createing user at the same time, so you get the error `ERROR 1410 (42000): You are not allowed to create a user with GRANT`
# https://www.percona.com/doc/percona-xtrabackup/8.0/using_xtrabackup/privileges.html#other-connection-options
- name: users | Grant Percona Backup User
  shell: "mysql -e \"GRANT BACKUP_ADMIN, PROCESS, RELOAD, LOCK TABLES, REPLICATION CLIENT ON *.* TO '{{ percona_xtrabackup_user.name }}'@'localhost';\" -uroot -p'{{ passwd_mysql_root }}'"
- shell: "mysql -e \"GRANT SELECT ON performance_schema.log_status TO '{{ percona_xtrabackup_user.name }}'@'localhost';\" -uroot -p'{{ passwd_mysql_root }}'"
- shell: "mysql -e \"FLUSH PRIVILEGES;\" -uroot -p'{{ passwd_mysql_root }}'"
