- name: check group existance
  shell: "getent group {{ applicationgroup.group.name }}"
  register: group_exitence
  failed_when: group_exitence.rc not in [ 0, 2 ]

- name: create application group
  group:
    name: "{{ applicationgroup.group.name }}"
    gid: "{{ applicationgroup.group.gid }}"
  when: group_exitence.rc == 0

- name: add application users
  user:
    name: "{{ applicationgroup.user.name }}"
    uid: "{{ applicationgroup.user.uid }}"
    create_home: no
    shell: /bin/false

# expect form like as " users docker "
- name: check user existance in groups
  shell: 'groups app | echo "$(cut -d: -f 2) "'
  register: user_exitence_in_group

- name: add users that join to group
  user:
    name: "{{ applicationgroup.user.name }}"
    groups: "{{ item }}"
    append: true
  when: item not in user_exitence_in_group.stdout_lines
  with_items:
    - " {{ applicationgroup.group.name }} "
