- name: Add zabbix monitor user
  shell: "mysql -e \"CREATE USER IF NOT EXISTS '{{mysql_user.zabbix_monitor.user}}'@'%' IDENTIFIED BY '{{mysql_user.zabbix_monitor.password}}'; GRANT REPLICATION CLIENT,PROCESS,SHOW DATABASES,SHOW VIEW ON *.* TO '{{mysql_user.zabbix_monitor.user}}'@'%';\" --connect-expired-password -uroot -p'{{ passwd_mysql_root }}'"

- name: Create /var/lib/zabbix directory
  file:
    path: "/var/lib/zabbix"
    state: directory
    owner: "root"
    group: "root"
    mode: 0700

- name: Create /var/lib/zabbix/.my.cnf
  template:
    src: var/lib/zabbix/.my.cnf.j2
    dest: /var/lib/zabbix/.my.cnf
    owner: root
    group: root
    mode: 0644
    backup: true
