# https://cloud.google.com/storage/docs/gsutil_install#deb
- name: Update Yum with Cloud SDK repo information
  shell: |
    tee -a /etc/yum.repos.d/google-cloud-sdk.repo << EOM
    [google-cloud-sdk]
    name=Google Cloud SDK
    baseurl=https://packages.cloud.google.com/yum/repos/cloud-sdk-el7-x86_64
    enabled=1
    gpgcheck=1
    repo_gpgcheck=0
    gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg
          https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
    EOM

- name: Install the Google Cloud SDK
  yum:
    name: google-cloud-sdk
    state: present
