- name: Create /etc/zabbix/zabbix_agentd.conf
  template:
    src: etc/zabbix/zabbix_agentd.d/db_mysql.conf.j2
    dest: /etc/zabbix/zabbix_agentd.d/db_mysql.conf
    owner: root
    group: root
    mode: 0644
